import { EntityType, DataProperty } from '../metadata/entity-metadata.js';
import { EntityKey } from './entity-key.js';
import { config } from '../config/config.js';

interface IPropEntry {
  entityType: EntityType;
  propertyName: string;
  /** Keys are generated id values as strings. A Set: it records which ids are taken. */
  keyMap: Set<string>;
}

type ITempIdMap = Map<string, IPropEntry>;

/** Generates temporary key values for new entities - one added with an unset key when its type's
`autoGeneratedKeyType` is not `None`, or one passed to {@link EntityManager.generateTempKeyValue} -
and keeps a record of the temporary values the manager's entities hold, so that an import cannot
give a second entity one of them. Each {@link EntityManager} has its own, as
{@link EntityManager.keyGenerator}, and replaces it when cleared. To supply your own, pass a
subclass's constructor as `keyGeneratorCtor` in the {@link EntityManagerConfig}, and have its
`generateTempKeyValue` pass the value it makes to `super.generateTempKeyValue` as `valueIfAvail`,
so that the value is recorded; Breeze calls only {@link KeyGenerator.generateTempKeyValue}. */
/*
  @class KeyGenerator
  */
export class KeyGenerator {
  /** @hidden @internal */
  private _tempIdMap: ITempIdMap;


  /** Creates a generator that has handed out no values. An {@link EntityManager} creates its own
  from {@link EntityManagerConfig.keyGeneratorCtor}. */
  constructor() {
    // key is dataProperty.name + || + entityType.name, value is propEntry
    // propEntry = { entityType, propertyName, keyMap }
    // keyMap has key of the actual value ( as a string) and a value of null or the real id.
    this._tempIdMap = new Map();
  }


  /**
  Returns a unique 'temporary' id for the specified {@link EntityType}.
  Uniqueness is defined for this purpose as being unique within each instance of a KeyGenerator. This is sufficient
  because each EntityManager will have its own instance of a KeyGenerator and any entities imported into
  the EntityManager with temporary keys will have them regenerated and remapped on import.

  The return value of this method must be of the correct type as determined by the keyProperties of the
  specified EntityType
  @example
      // Assume em1 is a preexisting EntityManager, and the server generates Order keys
      const order1 = em1.createEntity(Order);
      // next line calls em1.keyGenerator.generateTempKeyValue(order1.entityType),
      // sets order1's 'orderID' property to the result, and returns it
      const oid1 = em1.generateTempKeyValue(order1);
      const saveResult = await em1.saveChanges();
      const sameOrder1 = saveResult.entities[0];
      // order1 === sameOrder1;
      // but order1.orderID != oid1
      // because the server will have generated a new id
      // and the client will have been updated with this
      // new id.
  @param entityType - The type to generate a key for. Its key must be a single property.
  @param valueIfAvail - A key value to use if no entity in the manager holds it. When entities with
  temporary keys are imported, the manager passes each one's key here, so that the key survives the
  import where it can; a subclass passes the value it made. If the value is taken, or omitted, a new
  one is generated. Either way, the value returned is recorded as held.
  @returns The key value, of the key property's data type.
  */
  generateTempKeyValue(entityType: EntityType, valueIfAvail?: any): any {
    let keyProps = entityType.keyProperties;
    if (keyProps.length > 1) {
      throw new Error("Ids can not be autogenerated for entities with multipart keys");
    }
    let keyProp = keyProps[0];
    let propEntry = this._getPropEntry(keyProp, true);
    let nextId: any;
    if (valueIfAvail != null) {
      if (!propEntry.keyMap.has(valueIfAvail.toString())) {
        nextId = valueIfAvail;
      }
    }

    if (nextId === undefined) {
      let dataType = keyProp.dataType;
      let getNextFn = (dataType as any).getNext;
      if (getNextFn) {
        nextId = getNextFn(this);
        // need to watch out for collision with previously imported ids that might also get generated.
        while (propEntry.keyMap.has(nextId.toString())) {
          nextId = getNextFn(this);
        }
      } else {
        throw new Error("Cannot use a property with a dataType of: " + dataType.toString() + " for id generation");
      }
    }

    propEntry.keyMap.add(nextId.toString());
    return nextId;
  }

  /** Returns an {@link EntityKey} for each temporary key value the manager's entities hold: the
  values this generator handed out or recorded, less those released when an entity was saved and
  given the server's key, or detached.
  @deprecated Ask the entities instead:
  `em.getEntities().filter(e => e.entityAspect.hasTempKey).map(e => e.entityAspect.getKey())`.
  Breeze does not call it. It still works; it is not scheduled for removal. */
  getTempKeys() {
    let results: EntityKey[] = [];
    //noinspection JSHint
    this._tempIdMap.forEach(propEntry => {
      const entityType = propEntry.entityType;
      propEntry.keyMap.forEach(keyValue => {
        results.push(new EntityKey(entityType, [keyValue]));
      });
    });
    return results;
  }


  // proto methods below are not part of the KeyGenerator interface.

  /** Whether `entityKey`'s value is a temporary key an entity in the manager holds - one of the
  values {@link KeyGenerator.getTempKeys} returns. Always false for a multipart key.
  @deprecated Ask the entity instead: `em.getEntityByKey(key)?.entityAspect.hasTempKey`, or
  {@link EntityAspect.hasTempKey} when you have the entity. Breeze does not call it. It still
  works; it is not scheduled for removal. */
  isTempKey(entityKey: EntityKey) {
    let keyProps = entityKey.entityType.keyProperties;
    if (keyProps.length > 1) return false;
    let keyProp = keyProps[0];
    let propEntry = this._getPropEntry(keyProp);
    if (!propEntry) {
      return false;
    }
    return propEntry.keyMap.has(entityKey.values[0].toString());
  }

  /**
  Forgets a temporary key value that no entity holds any longer: the manager calls it when an
  entity with a temporary key is saved, and the server's key replaces it, or is detached. The value
  is then free for an import to keep. Without this the generator remembered every value it had
  ever handed out, for the life of the manager.
  @hidden @internal
  */
  _releaseTempKeyValue(entityType: EntityType, value: any) {
    const keyProps = entityType.keyProperties;
    if (keyProps.length !== 1 || value == null) return;
    this._getPropEntry(keyProps[0])?.keyMap.delete(value.toString());
  }

  /**
  Records a temporary key value this generator did not hand out, or has forgotten: the manager
  calls it when an entity that already has a temporary key is attached - one detached earlier, or
  one from another manager - so that an import cannot give a second entity the same key.
  @hidden @internal
  */
  _reserveTempKeyValue(entityType: EntityType, value: any) {
    const keyProps = entityType.keyProperties;
    if (keyProps.length !== 1 || value == null) return;
    this._getPropEntry(keyProps[0], true).keyMap.add(value.toString());
  }

  /** @hidden @internal */
  private _getPropEntry(keyProp: DataProperty, createIfMissing: true): IPropEntry;
  private _getPropEntry(keyProp: DataProperty, createIfMissing?: boolean): IPropEntry | undefined;
  private _getPropEntry(keyProp: DataProperty, createIfMissing = false) {
    let key = keyProp.name + ".." + keyProp.parentType.name;
    let propEntry = this._tempIdMap.get(key);
    if (!propEntry) {
      if (createIfMissing) {
        propEntry = { entityType: keyProp.parentType as EntityType, propertyName: keyProp.name, keyMap: new Set() };
        this._tempIdMap.set(key, propEntry);
      }
    }
    return propEntry;
  }

}

config.registerType(KeyGenerator, "KeyGenerator");

