import { AbstractDataServiceAdapter } from './abstract-data-service-adapter.js';
import { config as globalConfig, BreezeConfig } from '../config/config.js';
import { AutoGeneratedKeyType, DataProperty, MetadataStore } from '../metadata/entity-metadata.js';
import type { SaveContext, SaveBundle, KeyMapping } from '../manager/entity-manager.js';
import { JsonResultsAdapter } from '../metadata/data-service.js';
import type { NodeContext } from '../metadata/data-service.js';
import { MappingContext } from '../query/mapping-context.js';
import { DataType } from '../metadata/data-type.js';

/** @hidden */
export class DataServiceWebApiAdapter extends AbstractDataServiceAdapter {

  constructor() {
    super();
    this.name = "webApi";
  }

  static register(config?: BreezeConfig) {
    config = config || globalConfig;
    config.registerAdapter("dataService", DataServiceWebApiAdapter);
    return config.initializeAdapterInstance("dataService", "webApi", true) as DataServiceWebApiAdapter;
  }

  /** @hidden @internal */
  _prepareSaveBundle(saveContext: SaveContext, saveBundle: SaveBundle) {
    let changeRequestInterceptor = this._createChangeRequestInterceptor(saveContext, saveBundle);
    let em = saveContext.entityManager;
    let metadataStore = em.metadataStore;
    let helper = em.helper;
    let serSaveBundle: any = {};
    serSaveBundle.entities = saveBundle.entities.map(function (e, ix) {
      let rawEntity = helper.unwrapInstance(e, transformValue);

      let autoGeneratedKey: Object | undefined;
      if (e.entityType.autoGeneratedKeyType !== AutoGeneratedKeyType.None) {
        autoGeneratedKey = {
          propertyName: e.entityType.keyProperties[0].nameOnServer,
          autoGeneratedKeyType: e.entityType.autoGeneratedKeyType.name
        };
      }

      let originalValuesOnServer = helper.unwrapOriginalValues(e, metadataStore);
      rawEntity.entityAspect = {
        entityTypeName: e.entityType.name,
        defaultResourceName: e.entityType.defaultResourceName,
        entityState: e.entityAspect.entityState.name,
        originalValuesMap: originalValuesOnServer,
        autoGeneratedKey: autoGeneratedKey
      };
      rawEntity = changeRequestInterceptor.getRequest(rawEntity, e, ix);
      return rawEntity;
    });

    serSaveBundle.saveOptions = { tag: saveBundle.saveOptions.tag };
    changeRequestInterceptor.done(serSaveBundle.entities);
    return serSaveBundle;
  }

  /** @hidden @internal */
  _prepareSaveResult(saveContext: SaveContext, data: any) {
    // use the jsonResultAdapter to extractResults and extractKeyMappings
    let jra = saveContext.dataService.jsonResultsAdapter || this.jsonResultsAdapter;
    let entities = jra.extractSaveResults(data) || [];
    let keyMappings: KeyMapping[] = jra.extractKeyMappings(data) || [];
    let deletedKeys = jra.extractDeletedKeys ? (jra.extractDeletedKeys(data)) || [] : [];

    if (keyMappings.length) {
      // HACK: need to change the 'case' of properties in the saveResult
      // but KeyMapping properties internally are still ucase. ugh...
      keyMappings = keyMappings.map(function (km) {
        if (km.entityTypeName) return km; // it's already lower case
        let kmHack = km as any;
        let entityTypeName = MetadataStore.normalizeTypeName(kmHack.EntityTypeName);
        return { entityTypeName: entityTypeName, tempValue: kmHack.TempValue, realValue: kmHack.RealValue };
      });
    }

    if (deletedKeys.length) {
      deletedKeys = deletedKeys.map(function (dk) {
        if (dk.entityTypeName) return dk; // it's already lower case
        let entityTypeName = MetadataStore.normalizeTypeName(dk.EntityTypeName);
        // NOTE the dk.KeyValue => keyValues transition - needed because we are deserializing an .NET EntityKey
        return { entityTypeName: entityTypeName, keyValues: dk.KeyValue };
      });
    }

    return { entities: entities, keyMappings: keyMappings, deletedKeys: deletedKeys };

  }

  jsonResultsAdapter: JsonResultsAdapter = new JsonResultsAdapter({

    name: "webApi_default",

    visitNode: function (node: any, mappingContext: MappingContext, nodeContext: NodeContext) {
      if (node == null) return {};
      let entityTypeName = MetadataStore.normalizeTypeName(node.$type);
      let entityType = entityTypeName && mappingContext.entityManager.metadataStore.getEntityType(entityTypeName, true);
      let propertyName = nodeContext.propertyName;
      let ignore = propertyName && propertyName.substr(0, 1) === "$";

      return {
        entityType: entityType,
        nodeId: node.$id,
        nodeRefId: node.$ref,
        ignore: ignore
      } as any;
    }

  });

}

/** Transform data properties while unwrapping entities before save */
function transformValue(prop: DataProperty, val: any) {
  if (prop.dataType === DataType.DateOnly) {
    val = DataType.toDateOnlyString(val);
  }
  return val;
}


// NOTE: this module deliberately does NOT register itself on import.
// Registration is explicit - pass the adapter to configureBreeze, or call
// SomeAdapter.register(). Importing a module should not mutate global state.

