import { defineConfig } from 'vitepress';
import typedocSidebar from '../api/typedoc-sidebar.json';

export default defineConfig({
  title: 'Breeze',
  description: 'Data management for JavaScript clients',
  lang: 'en-US',
  cleanUrls: true,
  lastUpdated: true,

  // The API reference is generated by TypeDoc before the site builds.
  ignoreDeadLinks: false,

  themeConfig: {
    search: { provider: 'local' },

    nav: [
      { text: 'Guide', link: '/guide/what-is-breeze' },
      { text: 'Querying', link: '/query/' },
      { text: 'API', link: '/api/' },
      { text: 'Migrating from 2.x', link: '/guide/migrating-from-2x' },
      {
        text: 'Server',
        items: [
          { text: '.NET server docs', link: 'https://github.com/Breeze/breeze-server-v3' },
          { text: '.NET API reference', link: 'https://github.com/Breeze/breeze-server-v3/blob/master/DOCS.md' },
        ],
      },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'What is Breeze?', link: '/guide/what-is-breeze' },
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'Configuration', link: '/guide/configuration' },
            { text: 'Migrating from 2.x', link: '/guide/migrating-from-2x' },
          ],
        },
        {
          text: 'Core concepts',
          items: [
            { text: 'Inside the entity', link: '/guide/inside-the-entity' },
            { text: 'Creating entities', link: '/guide/creating-entities' },
            { text: 'Navigation properties', link: '/guide/navigation-properties' },
            { text: 'Complex properties', link: '/guide/complex-properties' },
            { text: 'Change tracking', link: '/guide/change-tracking' },
            { text: 'EntityManager and caching', link: '/guide/entitymanager-and-caching' },
            { text: 'Saving changes', link: '/guide/saving-changes' },
            { text: 'Validation', link: '/guide/validation' },
            { text: 'Export and import', link: '/guide/export-import' },
          ],
        },
        {
          text: 'Advanced',
          items: [
            { text: 'Extending entities', link: '/guide/extending-entities' },
            { text: 'Typed entities', link: '/guide/typed-entities' },
            { text: 'Date and time', link: '/guide/date-and-time' },
            { text: 'Performance', link: '/guide/performance' },
            { text: 'Testing', link: '/guide/testing' },
          ],
        },
      ],

      '/query/': [
        {
          text: 'Querying',
          items: [
            { text: 'Overview', link: '/query/' },
            { text: 'Query examples', link: '/query/examples' },
            { text: 'Where clauses', link: '/query/predicates' },
            { text: 'Ordering, paging, expand', link: '/query/shaping' },
            { text: 'Projections', link: '/query/projections' },
            { text: 'Querying the cache', link: '/query/locally' },
            { text: 'Debugging queries', link: '/query/debugging' },
          ],
        },
      ],

      '/metadata/': [
        {
          text: 'Metadata',
          items: [
            { text: 'Overview', link: '/metadata/' },
            { text: 'Metadata in depth', link: '/metadata/details' },
            { text: 'Writing metadata by hand', link: '/metadata/by-hand' },
            { text: 'Custom metadata', link: '/metadata/custom' },
          ],
        },
      ],

      '/server/': [
        {
          text: 'Talking to the server',
          items: [
            { text: 'Overview', link: '/server/' },
            { text: 'Supplying your own transport', link: '/server/transport' },
            { text: 'DataServiceAdapter', link: '/server/dataserviceadapter' },
            { text: 'Transforming JSON results', link: '/server/jsonresultsadapter' },
            { text: 'Naming conventions', link: '/server/namingconvention' },
          ],
        },
      ],

      '/api/': typedocSidebar,
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/Breeze/breeze-client-v3' },
    ],

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © IdeaBlade',
    },

    editLink: {
      pattern: 'https://github.com/Breeze/breeze-client-v3/edit/master/docs/:path',
      text: 'Edit this page on GitHub',
    },
  },
});
