
import { AbstractDataServiceAdapter } from './abstract-data-service-adapter.js';
import { assertParam, assertConfig, Param } from './assert-param.js';
import { BreezeConfig } from './config.js';
import { BreezeEnum } from './enum.js';
import { BreezeEvent } from './event.js';
import type { ComplexArray } from './complex-array.js';
import { DataService, JsonResultsAdapter } from './data-service.js';
import type { DataServiceConfig, JsonResultsAdapterConfig, NodeContext, NodeMeta } from './data-service.js';
import { DataType } from './data-type.js';
import { EntityAction } from './entity-action.js';
import { EntityAspect, ComplexAspect } from './entity-aspect.js';
import type { Entity, ComplexObject, StructuralObject, PropertyChangedEventArgs } from './entity-aspect.js';
import { EntityKey } from './entity-key.js';
import { EntityManager } from './entity-manager.js';
import type { EntityManagerConfig, EntityError, EntityChangedEventArgs, SaveContext, SaveBundle, HttpResponse, KeyMapping, ServerError, SaveResult, QueryResult, ValidationErrorsChangedEventArgs, HasChangesChangedEventArgs } from './entity-manager.js';
import { EntityQuery, FilterQueryOp, BooleanQueryOp, OrderByClause, ExpandClause, SelectClause } from './entity-query.js';
import { EntityState } from './entity-state.js';
import { InterfaceRegistry } from './interface-registry.js';
import type { AjaxAdapter, AjaxConfig, BreezeFetch, DataServiceAdapter, ModelLibraryAdapter, ChangeRequestInterceptor, UriBuilderAdapter, InterfaceRegistryConfig, AjaxRequestInterceptor } from './interface-registry.js';
import { KeyGenerator } from './key-generator.js';
import { LocalQueryComparisonOptions } from './local-query-comparison-options.js';
import { MappingContext } from './mapping-context.js';
import { MetadataStore, EntityType, ComplexType, DataProperty, NavigationProperty, AutoGeneratedKeyType } from './entity-metadata.js';
import type { StructuralType, EntityProperty } from './entity-metadata.js';
import { NamingConvention } from './naming-convention.js';
import { Predicate, UnaryPredicate, BinaryPredicate, AnyAllPredicate, AndOrPredicate, LitExpr, FnExpr, PropExpr } from './predicate.js';
import type { VisitContext, Visitor, ExpressionContext } from './predicate.js';
import { QueryOptions, FetchStrategy, MergeStrategy } from './query-options.js';
import { SaveOptions } from './save-options.js';
import { ValidationError, Validator } from './validate.js';
import { ValidationOptions } from './validation-options.js';

import { config } from './config.js';
import type { BaseAdapter } from './config.js';
import { configureBreeze } from './configure.js';
import type { BreezeSetupOptions, AdapterRegistration, AjaxAdapterRegistration } from './configure.js';
import { core } from './core.js';
import type { Callback, ErrorCallback } from './core.js';
import { makeRelationArray, makePrimitiveArray, makeComplexArray } from './array.js';

import type { RelationArray } from './relation-array.js';
import type { ArrayChangedArgs } from './observable-array.js';

// Fills the fallback table, so that Breeze works with no adapter registration. It registers
// nothing itself: see default-adapters.ts.
import './default-adapters.js';
export { BreezeConfig };
export type { ComplexArray, RelationArray };

export {
  AbstractDataServiceAdapter,
  AndOrPredicate,
  AnyAllPredicate,
  assertConfig,
  assertParam,
  AutoGeneratedKeyType,
  BinaryPredicate,
  BreezeEnum,
  BreezeEvent,
  ComplexAspect,
  ComplexType,
  config,
  configureBreeze,
  core,
  DataProperty,
  DataService,
  DataType,
  EntityAction,
  EntityAspect,
  EntityKey,
  EntityManager,
  EntityQuery,
  EntityState,
  EntityType,
  ExpandClause,
  FetchStrategy,
  FilterQueryOp,
  FnExpr,
  InterfaceRegistry,
  JsonResultsAdapter,
  KeyGenerator,
  LitExpr,
  LocalQueryComparisonOptions,
  makeComplexArray,
  makePrimitiveArray,
  makeRelationArray,
  MappingContext,
  MergeStrategy,
  MetadataStore,
  NamingConvention,
  NavigationProperty,
  OrderByClause,
  Predicate,
  PropExpr,
  QueryOptions,
  SaveOptions,
  SelectClause,
  UnaryPredicate,
  ValidationError,
  ValidationOptions,
  Validator,
};

// Type-only exports. These are erased at runtime, so they must be re-exported
// with `export type`: a bundler transpiling file-by-file cannot tell otherwise,
// and emits a runtime export that does not exist. Browser ESM rejects that.
export type {
  AjaxAdapter,
  AjaxConfig,
  AjaxRequestInterceptor,
  ArrayChangedArgs,
  BaseAdapter,
  BreezeFetch,
  Callback,
  ChangeRequestInterceptor,
  ComplexObject,
  BreezeSetupOptions,
  AdapterRegistration,
  AjaxAdapterRegistration,
  DataServiceAdapter,
  DataServiceConfig,
  Entity,
  EntityChangedEventArgs,
  EntityError,
  EntityManagerConfig,
  EntityProperty,
  ErrorCallback,
  ExpressionContext,
  HasChangesChangedEventArgs,
  HttpResponse,
  InterfaceRegistryConfig,
  JsonResultsAdapterConfig,
  KeyMapping,
  ModelLibraryAdapter,
  NodeContext,
  NodeMeta,
  PropertyChangedEventArgs,
  QueryResult,
  SaveBundle,
  SaveContext,
  SaveResult,
  ServerError,
  StructuralObject,
  StructuralType,
  UriBuilderAdapter,
  ValidationErrorsChangedEventArgs,
  VisitContext,
  Visitor,
};

// create a breeze variable here
export const breeze = {
  AbstractDataServiceAdapter: AbstractDataServiceAdapter,
  assertConfig: null as any,
  assertParam: null as any,
  AutoGeneratedKeyType: AutoGeneratedKeyType,
  BooleanQueryOp: BooleanQueryOp,
  ComplexAspect: ComplexAspect,
  ComplexType: ComplexType,
  config: config,
  core: core,
  DataProperty: DataProperty,
  DataService: DataService,
  DataType: DataType,
  EntityAction: EntityAction,
  EntityAspect: EntityAspect,
  EntityKey: EntityKey,
  EntityManager: EntityManager,
  EntityQuery: EntityQuery,
  EntityState: EntityState,
  EntityType: EntityType,
  Event: BreezeEvent,
  FetchStrategy: FetchStrategy,
  FilterQueryOp: FilterQueryOp,
  InterfaceRegistry: InterfaceRegistry,
  JsonResultsAdapter: JsonResultsAdapter,
  KeyGenerator: KeyGenerator,
  LocalQueryComparisonOptions: LocalQueryComparisonOptions,
  makeComplexArray: makeComplexArray,
  makePrimitiveArray: makePrimitiveArray,
  makeRelationArray: makeRelationArray,
  MergeStrategy: MergeStrategy,
  MetadataStore: MetadataStore,
  NamingConvention: NamingConvention,
  NavigationProperty: NavigationProperty,
  OrderByClause: OrderByClause, // for testing only
  Param,
  Predicate: Predicate,
  QueryOptions: QueryOptions,
  SaveOptions: SaveOptions,
  ValidationError: ValidationError,
  ValidationOptions: ValidationOptions,
  Validator: Validator,
  version: "2.1.5"
};

// breeze.assertConfig = assertConfig as any;
// breeze.assertParam = assertParam as any;

// Shapes that public signatures accept or return: constructor config objects, event args,
// callbacks, and what adapter authors implement against. Type-only, so no runtime cost -
// exported so applications can name them.
export type { AdapterCtor, AdapterType } from './config.js';
export type { AjaxRequest, ChangeRequestInterceptorCtor } from './interface-registry.js';
export type {
  ComplexTypeConfig, DataPropertyConfig, EntityTypeConfig, EntityTypeSetConfig,
  MetadataFetchedEventArgs, MetadataStoreConfig, NavigationPropertyConfig,
} from './entity-metadata.js';
export type {
  IEntityByKeyResult, ImportConfig, ImportResult, ITempKeyMap, QueryErrorCallback, QuerySuccessCallback, SaveError,
} from './entity-manager.js';
export type { LocalQueryComparisonOptionsConfig } from './local-query-comparison-options.js';
export type { NamingConventionConfig } from './naming-convention.js';
export type { QueryOptionsConfig } from './query-options.js';
export type { SaveOptionsConfig } from './save-options.js';
export type { ValidationContext, ValidationFn, ValidationMessageContext } from './validate.js';
export type { ValidationOptionsConfig } from './validation-options.js';

export namespace promises {
  /** no-op for backward compatibility with breeze-bridge2-angular */
  export interface IPromiseService {}
}

/** @hidden @internal */
declare var window: any;

/** @hidden @internal */
declare var global: any;

/** @hidden @internal */
let win: any;
try {
  win = window ? window : (global ? global.window : undefined);
} catch (e) {

}
if (win) {
  win.breeze = breeze;
}
