
import { AbstractDataServiceAdapter } from './adapters/abstract-data-service-adapter.js';
import { assertParam, assertConfig, Param } from './core/assert-param.js';
import { BreezeConfig } from './config/config.js';
import { BreezeEnum } from './core/enum.js';
import { BreezeEvent } from './core/event.js';
import type { ComplexArray } from './entity/complex-array.js';
import { DataService, JsonResultsAdapter } from './metadata/data-service.js';
import type { DataServiceConfig, JsonResultsAdapterConfig, NodeContext, NodeMeta } from './metadata/data-service.js';
import { DataType } from './metadata/data-type.js';
import { EntityAction } from './entity/entity-action.js';
import { EntityAspect, ComplexAspect } from './entity/entity-aspect.js';
import type { Entity, ComplexObject, StructuralObject, PropertyChangedEventArgs, QueriedAs } from './entity/entity-aspect.js';
import { EntityKey } from './entity/entity-key.js';
import { EntityManager, ProblemTypes, isConcurrencyError } from './manager/entity-manager.js';
import type { EntityManagerConfig, EntityError, EntityChangedEventArgs, SaveContext, SaveBundle, HttpResponse, KeyMapping, ServerError, SaveResult, QueryResult, ValidationErrorsChangedEventArgs, HasChangesChangedEventArgs } from './manager/entity-manager.js';
import { EntityQuery, FilterQueryOp, BooleanQueryOp, OrderByClause, ExpandClause, SelectClause } from './query/entity-query.js';
import { EntityState } from './entity/entity-state.js';
import { InterfaceRegistry } from './config/interface-registry.js';
import type { AjaxAdapter, AjaxConfig, BreezeFetch, DataServiceAdapter, ModelLibraryAdapter, ChangeRequestInterceptor, UriBuilderAdapter, InterfaceRegistryConfig, AjaxRequestInterceptor } from './config/interface-registry.js';
import { KeyGenerator } from './entity/key-generator.js';
import { LocalQueryComparisonOptions } from './metadata/local-query-comparison-options.js';
import { MappingContext } from './query/mapping-context.js';
import { MetadataStore, EntityType, ComplexType, DataProperty, NavigationProperty, AutoGeneratedKeyType, entityTypeForCtor } from './metadata/entity-metadata.js';
import type { StructuralType, EntityProperty } from './metadata/entity-metadata.js';
import { NamingConvention } from './metadata/naming-convention.js';
import { Predicate, UnaryPredicate, BinaryPredicate, AnyAllPredicate, AndOrPredicate, LitExpr, FnExpr, PropExpr } from './query/predicate.js';
import type { VisitContext, Visitor, ExpressionContext } from './query/predicate.js';
import { QueryOptions, FetchStrategy, MergeStrategy } from './query/query-options.js';
import { SaveOptions } from './manager/save-options.js';
import { ValidationError, Validator } from './validation/validate.js';
import { ValidationOptions } from './validation/validation-options.js';

import { config } from './config/config.js';
import type { BaseAdapter } from './config/config.js';
import { configureBreeze } from './config/configure.js';
import type { BreezeSetupOptions, AdapterRegistration, AjaxAdapterRegistration } from './config/configure.js';
import { core } from './core/core.js';
import type { Callback, ErrorCallback } from './core/core.js';
import { makeRelationArray, makePrimitiveArray, makeComplexArray } from './entity/array.js';

import type { RelationArray } from './entity/relation-array.js';
import type { ArrayChangedArgs } from './entity/observable-array.js';

export { BreezeConfig };
export type { ComplexArray, RelationArray };

export {
  AbstractDataServiceAdapter,
  AndOrPredicate,
  AnyAllPredicate,
  assertConfig,
  assertParam,
  AutoGeneratedKeyType,
  BinaryPredicate,
  BreezeEnum,
  BreezeEvent,
  ComplexAspect,
  ComplexType,
  config,
  configureBreeze,
  core,
  DataProperty,
  DataService,
  DataType,
  EntityAction,
  EntityAspect,
  EntityKey,
  EntityManager,
  EntityQuery,
  EntityState,
  EntityType,
  entityTypeForCtor,
  ExpandClause,
  FetchStrategy,
  FilterQueryOp,
  FnExpr,
  InterfaceRegistry,
  JsonResultsAdapter,
  KeyGenerator,
  LitExpr,
  LocalQueryComparisonOptions,
  makeComplexArray,
  makePrimitiveArray,
  makeRelationArray,
  MappingContext,
  MergeStrategy,
  MetadataStore,
  NamingConvention,
  NavigationProperty,
  OrderByClause,
  Predicate,
  PropExpr,
  QueryOptions,
  SaveOptions,
  SelectClause,
  UnaryPredicate,
  ValidationError,
  ValidationOptions,
  Validator,
  ProblemTypes,
  isConcurrencyError,
};

// Type-only exports. These are erased at runtime, so they must be re-exported
// with `export type`: a bundler transpiling file-by-file cannot tell otherwise,
// and emits a runtime export that does not exist. Browser ESM rejects that.
export type {
  AjaxAdapter,
  AjaxConfig,
  AjaxRequestInterceptor,
  ArrayChangedArgs,
  BaseAdapter,
  BreezeFetch,
  Callback,
  ChangeRequestInterceptor,
  ComplexObject,
  BreezeSetupOptions,
  AdapterRegistration,
  AjaxAdapterRegistration,
  DataServiceAdapter,
  DataServiceConfig,
  Entity,
  EntityChangedEventArgs,
  EntityError,
  EntityManagerConfig,
  EntityProperty,
  ErrorCallback,
  ExpressionContext,
  HasChangesChangedEventArgs,
  HttpResponse,
  InterfaceRegistryConfig,
  JsonResultsAdapterConfig,
  KeyMapping,
  ModelLibraryAdapter,
  NodeContext,
  NodeMeta,
  PropertyChangedEventArgs,
  QueriedAs,
  QueryResult,
  SaveBundle,
  SaveContext,
  SaveResult,
  ServerError,
  StructuralObject,
  StructuralType,
  UriBuilderAdapter,
  ValidationErrorsChangedEventArgs,
  VisitContext,
  Visitor,
};

/** Every class, enum and helper of the Breeze 2.x API in one object - the `breeze` that 2.x code
    imports or finds as a global. Kept so that code written against 2.x runs unchanged. New code
    imports what it uses by name, which lets a bundler leave out the rest. */
export const breeze = {
  /** The base class of Breeze's data service adapters, for anyone writing one. The same as the
      `AbstractDataServiceAdapter` export. */
  AbstractDataServiceAdapter: AbstractDataServiceAdapter,
  /** Always `null`. Breeze 2.x exposed its argument-checking helpers here; Breeze 3 does not. */
  assertConfig: null as any,
  /** Always `null`. Breeze 2.x exposed its argument-checking helpers here; Breeze 3 does not. */
  assertParam: null as any,
  /** The same as the {@link AutoGeneratedKeyType} export. */
  AutoGeneratedKeyType: AutoGeneratedKeyType,
  /** The operators that combine predicates in a query - `and`, `or` and `not` - as an enum. The
      same as the `BooleanQueryOp` export. */
  BooleanQueryOp: BooleanQueryOp,
  /** The same as the {@link ComplexAspect} export. */
  ComplexAspect: ComplexAspect,
  /** The same as the {@link ComplexType} export. */
  ComplexType: ComplexType,
  /** The same as the {@link config} export: the older adapter-registration API. New code calls
      {@link configureBreeze} instead. */
  config: config,
  /** The same as the {@link core} export. */
  core: core,
  /** The same as the {@link DataProperty} export. */
  DataProperty: DataProperty,
  /** The same as the {@link DataService} export. */
  DataService: DataService,
  /** The same as the {@link DataType} export. */
  DataType: DataType,
  /** The same as the {@link EntityAction} export. */
  EntityAction: EntityAction,
  /** The same as the {@link EntityAspect} export. */
  EntityAspect: EntityAspect,
  /** The same as the {@link EntityKey} export. */
  EntityKey: EntityKey,
  /** The same as the {@link EntityManager} export. */
  EntityManager: EntityManager,
  /** The same as the {@link EntityQuery} export. */
  EntityQuery: EntityQuery,
  /** The same as the {@link EntityState} export. */
  EntityState: EntityState,
  /** The same as the {@link EntityType} export. */
  EntityType: EntityType,
  /** The same as the {@link BreezeEvent} export, under its 2.x name. */
  Event: BreezeEvent,
  /** The same as the {@link FetchStrategy} export. */
  FetchStrategy: FetchStrategy,
  /** The same as the {@link FilterQueryOp} export. */
  FilterQueryOp: FilterQueryOp,
  /** The same as the {@link InterfaceRegistry} export. */
  InterfaceRegistry: InterfaceRegistry,
  /** The same as the {@link JsonResultsAdapter} export. */
  JsonResultsAdapter: JsonResultsAdapter,
  /** The same as the {@link KeyGenerator} export. */
  KeyGenerator: KeyGenerator,
  /** The same as the {@link LocalQueryComparisonOptions} export. */
  LocalQueryComparisonOptions: LocalQueryComparisonOptions,
  /** Turns an array into the array behind a collection of complex objects. For model library
      adapter authors; Breeze's own adapter calls it when it sets up an entity. */
  makeComplexArray: makeComplexArray,
  /** Turns an array into the array behind a collection of primitive values. For model library
      adapter authors; Breeze's own adapter calls it when it sets up an entity. */
  makePrimitiveArray: makePrimitiveArray,
  /** Turns an array into the {@link RelationArray} behind a collection navigation property. For
      model library adapter authors; Breeze's own adapter calls it when it sets up an entity. */
  makeRelationArray: makeRelationArray,
  /** The same as the {@link MergeStrategy} export. */
  MergeStrategy: MergeStrategy,
  /** The same as the {@link MetadataStore} export. */
  MetadataStore: MetadataStore,
  /** The same as the {@link NamingConvention} export. */
  NamingConvention: NamingConvention,
  /** The same as the {@link NavigationProperty} export. */
  NavigationProperty: NavigationProperty,
  /** The class that holds a query's `orderBy`. Exposed for Breeze's own tests; applications do not
      need it. */
  OrderByClause: OrderByClause, // for testing only
  /** Breeze's internal argument-checking helper. Applications do not need it. */
  Param,
  /** The same as the {@link Predicate} export. */
  Predicate: Predicate,
  /** The same as the {@link QueryOptions} export. */
  QueryOptions: QueryOptions,
  /** The same as the {@link SaveOptions} export. */
  SaveOptions: SaveOptions,
  /** The same as the {@link ValidationError} export. */
  ValidationError: ValidationError,
  /** The same as the {@link ValidationOptions} export. */
  ValidationOptions: ValidationOptions,
  /** The same as the {@link Validator} export. */
  Validator: Validator,
  /** The version of `breeze-client`. A test keeps it equal to the one in package.json. */
  version: "3.0.0"
};

// breeze.assertConfig = assertConfig as any;
// breeze.assertParam = assertParam as any;

// Shapes that public signatures accept or return: constructor config objects, event args,
// callbacks, and what adapter authors implement against. Type-only, so no runtime cost -
// exported so applications can name them.
export type { AdapterCtor, AdapterType } from './config/config.js';
export type { AjaxRequest, ChangeRequestInterceptorCtor } from './config/interface-registry.js';
export type {
  ComplexTypeConfig, DataPropertyConfig, EntityTypeConfig, EntityTypeSetConfig,
  MetadataFetchedEventArgs, MetadataStoreConfig, NavigationPropertyConfig,
} from './metadata/entity-metadata.js';
export type {
  EntityByKeyResult, EntityTypeArg, ExportEntitiesArg, IEntityByKeyResult, ImportConfig, ImportResult, InitialValues, ITempKeyMap,
  QueryErrorCallback, QuerySuccessCallback, SaveError,
} from './manager/entity-manager.js';
export type { LocalQueryComparisonOptionsConfig } from './metadata/local-query-comparison-options.js';
export type { NamingConventionConfig } from './metadata/naming-convention.js';
export type {
  CollectionElement, CollectionPath, FilterOpFor, FilterValueExpression, FilterValueFor, FunctionExpressionPath,
  FilterClause, FilterOpsObject, FilterOpNameFor, NavigationPath, OrderByPath,
  KeyValues, PropertyPath, PropertyValue, QuantifierOp, SelectPath, WhereObject,
} from './query/property-path.js';
export type { TypedPredicateFactory } from './query/predicate.js';
export type { QueryOptionsConfig } from './query/query-options.js';
export type { SaveOptionsConfig } from './manager/save-options.js';
export type { ValidationContext, ValidationFn, ValidationMessageContext } from './validation/validate.js';
export type { ValidationOptionsConfig } from './validation/validation-options.js';

/** Kept for code written against Breeze 2.x and `breeze-bridge2-angular`. Breeze 3 uses native
    promises and has nothing to configure here. */
export namespace promises {
  /** An empty interface, kept so that code written for `breeze-bridge2-angular`, which named it,
      still compiles. Breeze 3 uses native promises. */
  export interface IPromiseService {}
}

/** @hidden @internal */
declare var window: any;

/** @hidden @internal */
declare var global: any;

// The 2.x global. Unbundled, this always runs. Under "sideEffects": false a bundler keeps it only
// when the bundle uses the `breeze` object above - which holds every class, so keeping it for
// every bundle would defeat tree-shaking. See CHANGES-DEV.md.
/** @hidden @internal */
let win: any;
try {
  win = window ? window : (global ? global.window : undefined);
} catch (e) {

}
if (win) {
  win.breeze = breeze;
}
